POST http://localhost:5101/tickets
Content-Type: application/json

{
    "Username": "JohnDoe312312",
    "Email": "Johndsad@hotmail.com",
    "Description": "I have AAAAAAA a problem with my ASP.NET build",
    "Tags": [
        ".NET622",
        "Build22",
        "Dev22"
    ]
}