@id=00000000-0000-0000-0000-000000000000

PUT http://localhost:5101/tickets/{{id}}
Content-Type: application/json

{
    "Username": "JohnDoe12",
    "Email": "John@hotmail.com",
    "Description": "I have a problem with my ASP.NET build",
    "SubmitDate": "2023-02-02T11:00:00",
    "Tags": [
        ".NET6",
        "Build",
        "Dev"
    ]
}